package eu.standardcode.heatmap.model;
// Generated Nov 12, 2011 6:14:32 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.*;

/**
 * Domain generated by hbm2java
 */
@Entity
@Table(name = "domain", catalog = "heatmap")
public class Domain implements java.io.Serializable {

    private Integer id;
    private String domain;
    private long appear;
    private Set<Url> urls = new HashSet<Url>(0);

    public Domain() {
    }

    public Domain(String domain) {
        this.domain = domain;
        this.appear = System.currentTimeMillis();
    }

    public Domain(String domain, long appear, Set<Url> urls) {
        this.domain = domain;
        this.appear = appear;
        this.urls = urls;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "domain", nullable = false)
    public String getDomain() {
        return this.domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    @Column(name = "appear", nullable = false)
    public long getAppear() {
        return this.appear;
    }

    public void setAppear(long appear) {
        this.appear = appear;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "domain")
    public Set<Url> getUrls() {
        return this.urls;
    }

    public void setUrls(Set<Url> urls) {
        this.urls = urls;
    }
}
