package eu.standardcode.heatmap.model;
// Generated Nov 12, 2011 6:14:32 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mousemove generated by hbm2java
 */
@Entity
@Table(name = "mousemove", catalog = "heatmap")
public class Mousemove extends MouseEvent {

    public Mousemove() {
    }

    public Mousemove(User user, Url url, short x, short y, long appear) {
        super(user, url, x, y, appear);
    }
}