package eu.standardcode.heatmap.model;
// Generated Nov 12, 2011 6:14:32 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mouseup generated by hbm2java
 */
@Entity
@Table(name = "mouseup", catalog = "heatmap")
public class Mouseup extends MouseEvent {

    public Mouseup() {
    }

    public Mouseup(User user, Url url, short x, short y, long appear) {
        super(user, url, x, y, appear);
    }
}