package eu.standardcode.heatmap.model;
// Generated Nov 12, 2011 6:14:32 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.*;

/**
 * Url generated by hbm2java
 */
@Entity
@Table(name = "url", catalog = "heatmap")
public class Url implements java.io.Serializable {

    private Integer id;
    private Domain domain;
    private String path;
    private long appear;
    private Set<Mouseup> mouseups = new HashSet<Mouseup>(0);
    private Set<Mousemove> mousemoves = new HashSet<Mousemove>(0);
    private Set<Mousedown> mousedowns = new HashSet<Mousedown>(0);

    public Url() {
    }

    public Url(Domain domain, String path) {
        this.domain = domain;
        this.path = path;
        this.appear = System.currentTimeMillis();
    }

    public Url(Domain domain, String path, long appear, Set<Mouseup> mouseups, Set<Mousemove> mousemoves, Set<Mousedown> mousedowns) {
        this.domain = domain;
        this.path = path;
        this.appear = appear;
        this.mouseups = mouseups;
        this.mousemoves = mousemoves;
        this.mousedowns = mousedowns;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "domain_id", nullable = false)
    public Domain getDomain() {
        return this.domain;
    }

    public void setDomain(Domain domain) {
        this.domain = domain;
    }

    @Column(name = "path", nullable = false)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name = "appear", nullable = false)
    public long getAppear() {
        return this.appear;
    }

    public void setAppear(long appear) {
        this.appear = appear;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "url")
    public Set<Mouseup> getMouseups() {
        return this.mouseups;
    }

    public void setMouseups(Set<Mouseup> mouseups) {
        this.mouseups = mouseups;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "url")
    public Set<Mousemove> getMousemoves() {
        return this.mousemoves;
    }

    public void setMousemoves(Set<Mousemove> mousemoves) {
        this.mousemoves = mousemoves;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "url")
    public Set<Mousedown> getMousedowns() {
        return this.mousedowns;
    }

    public void setMousedowns(Set<Mousedown> mousedowns) {
        this.mousedowns = mousedowns;
    }
}
